const { APP_TEXT } = require("./constants");

const SELECTORS = {
  // Login Form
  LOGIN_FORM: "[data-testid='login-form']",
  EMAIL_INPUT: "[data-testid='input-email']",
  PASSWORD_INPUT: "[data-testid='input-password']",
  SIGN_IN_BUTTON: `button:has-text('${APP_TEXT.SIGN_IN_LABEL}')`,
  REMEMBER_ME_CHECKBOX: "input[type='checkbox']",
  TOGGLE_PASSWORD: "[data-testid='toggle-password']",
  FORGOT_PASSWORD_LINK: "a:has-text('Forgot Password?')",

  // Error Messages
  EMAIL_ERROR: "[data-testid='email-error']",
  PASSWORD_ERROR: "[data-testid='password-error']",
  LOGIN_ERROR: "[data-testid='login-error']",

  // User Menu & Dashboard
  USER_MENU: "[data-testid='user-menu-btn']",
  ADMIN_DASHBOARD: "[data-testid='admin-dashboard']",
  SESSION_EXPIRED_MSG: "[data-testid='session-expired-msg']",

  // Registration Form
  REQUIRED_ERROR: ".form-error",
  REGISTRATION_FORM: "[data-testid='register-form']",
  REGISTRATION_FIRST_NAME_INPUT: "[data-testid='input-reg-first-name']",
  REGISTRATION_LAST_NAME_INPUT: "[data-testid='input-reg-last-name']",
  REGISTRATION_EMAIL_INPUT: "[data-testid='input-reg-email']",
  REGISTRATION_PASSWORD_INPUT: "[data-testid='input-reg-password']",
  REGISTRATION_CONFIRM_PASSWORD_INPUT: "[data-testid='input-reg-confirm-password']",
  REGISTRATION_PHONE_INPUT: "[data-testid='input-reg-phone']",
  CREATE_ACCOUNT_BUTTON: `button:has-text('${APP_TEXT.CREATE_ACCOUNT_BUTTON}')`,
  SIGN_IN_LINK: "a:has-text('Sign in')",
  PASSWORD_STRENGTH: "[data-testid='password-strength']",
  CONFIRM_PASSWORD_ERROR: "[data-testid='confirm-password-error']",
  REGISTRATION_SUCCESS_MESSAGE: `text=${APP_TEXT.REGISTRATION_SUCCESS_MESSAGE}`,

  // Product Catalog
  PRODUCT_GRID: "[data-testid='product-grid']",
  LIST_VIEW_BUTTON: "[data-testid='view-list']",
  GRID_VIEW_BUTTON: "[data-testid='view-grid']",
  PRODUCT_CARD: "[data-testid='product-card']",
  PRODUCT_COUNT: "[data-testid='product-count']",
  PRODUCTS_HEADING: `h1:has-text('${APP_TEXT.PRODUCT_HEADING}')`,
  PRODUCT_CATEGORY_FILTER: (category) => `[data-testid='filter-cat-${category}']`,
  PRODUCT_CATEGORY: "[data-testid='product-category']",
  SORT_DROPDOWN: "[data-testid='sort-select']",
  PRODUCT_PRICE: "[data-testid='product-price']",
  PRODUCT_SEARCH_INPUT: "[data-testid='nav-search-input']",
  PRODUCT_SEARCH_BUTTON: "[data-testid='nav-search-btn']",
  EMPTY_STATE: "[data-testid=\"empty-state\"]",
  NEXT_PAGE: "[data-testid=\"next-page\"]",
  PRODUCT_NAME: "[data-testid=\"product-name\"]",
  INFINITE_SCROLL_TOGGLE: "[data-testid=\"infinite-scroll-toggle\"]",
  OUT_OF_STOCK_BADGE: "[data-testid=\"out-of-stock-badge\"]",
  PRODUCT_DETAIL_NAME: "[data-testid=\"product-detail-name\"]",
  PRODUCT_DETAIL_PRICE: "[data-testid=\"product-detail-price\"]",
  PRODUCT_DETAIL_STOCK: "[data-testid=\"product-detail-stock\"]",
  PRODUCT_DETAIL_RATING: "[data-testid=\"star-rating\"]",

  //CART
  ADD_TO_CART_BUTTON: "[data-testid=\"add-to-cart-btn\"]",
  CART_COUNT: "[data-testid=\"cart-count\"]",
  ALERT: "alert",
  TOAST: ".Toastify__toast",
  CART_TOAST: "#cart-add",
  CART_QUANTITY: "[data-testid='cart-qty']",
  CART_QUANTITY_INCREASE: "[data-testid='qty-increase']",
  CART_QUANTITY_DECREASE: "[data-testid='qty-decrease']",
  REMOVE_ITEM_BUTTON: "[data-testid=\"remove-item-btn\"]",
  COUPON_INPUT: "[data-testid=\"coupon-input\"]",
  APPLY_COUPON_BUTTON: "[data-testid=\"apply-coupon-btn\"]",
  REMOVE_COUPON_BUTTON: "button:has-text(\"✕\")",
  COUPON_SUCCESS: "[data-testid=\"coupon-success\"]",
  DISCOUNT_AMOUNT: "[data-testid=\"discount-amount\"]",
  COUPON_ERROR: "[data-testid=\"coupon-error\"]",
  CART_SUBTOTAL: "[data-testid=\"cart-subtotal\"]",
  CART_TOTAL: "[data-testid=\"cart-total\"]",
  PROCEED_CHECKOUT_BUTTON: "[data-testid=\"proceed-checkout-btn\"]",

  //CHECK OUT
  CHECK_OUT_STEP: "[data-testid='step-indicator'] [data-testid^='step-']",
  CHECK_OUT_NEXT_STEP: "[data-testid=\"btn-next\"]",
  CHECK_OUT_FULL_NAME: "[data-testid=\"field-full-name\"]",
  CHECK_OUT_PHONE: "[data-testid=\"field-phone\"]",
  CHECK_OUT_ADDRESS_LINE1: "[data-testid=\"field-line1\"]",
  CHECK_OUT_CITY: "[data-testid=\"field-city\"]",
  CHECK_OUT_STATE: "[data-testid=\"field-state\"]",
  CHECK_OUT_POSTAL_CODE: "[data-testid=\"field-postal\"]",
  CHECK_OUT_DELIVERY_STEP: "[data-testid=\"step-delivery\"]",
  CHECK_OUT_DELIVERY_OPTION: (deliveryType) => `[data-testid="delivery-${deliveryType}"]`,
  CHECK_OUT_PAYMENT_STEP: "[data-testid=\"step-payment\"]",
  CHECK_OUT_PAYMENT_CREDIT_CARD: "[data-testid=\"payment-credit-card\"]",
  CHECK_OUT_CARD_NUMBER: "[data-testid=\"card-number\"]",
  CHECK_OUT_CARD_EXPIRY: "[data-testid=\"card-expiry\"]",
  CHECK_OUT_CARD_CVV: "[data-testid=\"card-cvv\"]",
  CHECK_OUT_CARD_NAME: "[data-testid=\"card-name\"]",
  CHECK_OUT_REVIEW_STEP: "[data-testid=\"step-review\"]",
  CHECK_OUT_PLACE_ORDER: "[data-testid=\"btn-place-order\"]",
  CHECK_OUT_DATE_PICKER_TRIGGER: "[data-testid=\"date-picker-trigger\"]",
  CHECK_OUT_DATE_PICKER_CALENDAR: "[data-testid=\"datepicker-calendar\"]",
  CHECK_OUT_DATE_PICKER_NEXT_MONTH: "[data-testid=\"dp-next-month\"]",
  CHECK_OUT_DATE_PICKER_DAY: "[data-testid^=\"dp-day-\"]",

  // ORDERS
  ORDERS_PAGE: "[data-testid=\"orders-page\"]",
  ORDER_STATUS_FILTER: "[data-testid=\"order-status-filter\"]",
  ORDER_STATUS_BADGE: "[data-testid=\"order-status-badge\"]",
  ORDERS_EMPTY_STATE: "h3:has-text(\"No orders yet\")",

  // ADMIN
  ADMIN_STATS_GRID: "[data-testid=\"stats-grid\"]",
  ADMIN_TOTAL_REVENUE: "[data-testid=\"stat-total-revenue\"]",
  ADMIN_TOTAL_ORDERS: "[data-testid=\"stat-total-orders\"]",
  ADMIN_TOTAL_USERS: "[data-testid=\"stat-total-users\"]",
  ADMIN_SIDEBAR_PRODUCTS: "[data-testid=\"sidebar-products\"]",
  ADMIN_ORDERS_TABLE: "[data-testid=\"orders-table\"]",
  ADMIN_ACCESS_DENIED: "text=Access Denied",
  ADMIN_ADD_PRODUCT_BUTTON: "[data-testid=\"btn-add-product\"]",
  ADMIN_PRODUCT_FORM_MODAL: "[data-testid=\"product-form-modal\"]",
  ADMIN_SAVE_PRODUCT_BUTTON: "[data-testid=\"btn-save-product\"]",
  ADMIN_PRODUCT_NAME_ERROR: "[data-testid=\"product-name-error\"]",
  ADMIN_IMAGE_DROPZONE: "[data-testid=\"image-dropzone\"]",
  ADMIN_CREATE_COUPON_BUTTON: "[data-testid=\"btn-create-coupon\"]",
  ADMIN_COUPON_CODE: "[data-testid=\"coupon-code\"]",
  ADMIN_COUPON_TYPE: "[data-testid=\"coupon-type\"]",
  ADMIN_COUPON_VALUE: "[data-testid=\"coupon-value\"]",
  ADMIN_COUPON_LIMIT: "[data-testid=\"coupon-limit\"]",
  ADMIN_SAVE_COUPON_BUTTON: "[data-testid=\"btn-save-coupon\"]",
  ADMIN_ERROR_TOAST: ".Toastify__toast--error",

  // INTERACTIVE AND ACCESSIBILITY
  HOME_SEARCH_REGION: "[data-testid=\"navbar\"] [role=\"search\"]",
  SEARCH_ACCESSIBLE_INPUT: "[data-testid=\"navbar\"] [aria-label=\"Search products\"]",
  ADMIN_CLOSE_MODAL_BUTTON: "button[aria-label=\"Close modal\"]",

  //DASHBOARD
  SEARCH_INPUT: "[data-testid='nav-search-input']",
  SEARCH_BUTTON: "[data-testid='nav-search-btn']",
};

module.exports = { SELECTORS };
